name: example
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.18.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_highlight: ^0.6.0
  http: ^0.13.5
  cupertino_icons: ^1.0.2
  flutter_markdown: ^0.6.14
  translator: ^0.1.7
  flutter_launcher_icons: ^0.12.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  intl: ^0.17.0
flutter_icons:
  android: true
  ios: true
  image_path: assets/images/logo.png
flutter:
  uses-material-design: true
  assets:
  - assets/images/
